sudo: true
dist: trusty
language: rust
matrix:
  include:
  - rust: nightly
script:
  - ./test/build_openssl.sh
  - ./test/build_kcov.sh
  - cargo update
  - cargo build -v
  - cargo test --no-run
  - kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/cov target/debug/lrad*
cache:
  cargo: true
  directories:
    - $HOME/openssl-1.1.1/
    - $HOME/kcov-master/
  timeout: 360
before_cache:
  - chmod -R a+r $HOME/.cargo
env:
  global:
  - OPENSSL_DIR=$HOME/openssl-1.1.1
addons:
  apt:
    update: true
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
