sudo: true
dist: trusty
language: rust
matrix:
  include:
  - rust: nightly
script:
  - ./test/build_openssl.sh
  - ./test/build_kcov.sh
  - cargo update
  - rm target/debug/lrad*
  - cargo build -v
  - cargo test --no-run
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo --exclude-path=/usr target/cov `find target/debug/ -maxdepth 1 -executable -type f`
cache:
  cargo: true
  directories:
    - $HOME/openssl-1.1.1/
    - $HOME/kcov-master/
  timeout: 360
before_cache:
  - chmod -R a+r $HOME/.cargo
env:
  global:
  - OPENSSL_DIR=$HOME/openssl-1.1.1
addons:
  apt:
    update: true
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
      - gcc
after_success:
  - openssl enc -pbkdf2 -aes-256-cbc -pass 'env:IPFS_OPENSSL_AES_KEY' -d -in ./ipfs_ssh_key.enc -out /tmp/ipfs_ssh_key
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/ipfs_ssh_key
  - ssh-add /tmp/ipfs_ssh_key
  - ./test/ipfs_deploy.sh
  