sudo: true
dist: trusty
language: rust
matrix:
  include:
- rust: nightly
script:
  - ./test/build_openssl.sh
  - cargo update
  - cargo build -v
  - cargo test
cache:
  cargo: true
  directories:
    - $HOME/openssl-1.1.1/
  timeout: 360
before_cache:
  - chmod -R a+r $HOME/.cargo
env:
  global:
  - OPENSSL_DIR=$HOME/openssl-1.1.1
addons:
  apt:
    update: true
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/lrad-*